steps:
  - id: Build the image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t=$_GCR_HOSTNAME/$PROJECT_ID/hello:$SHORT_SHA
      - .
  - id: Push the image to Artifact Registry
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GCR_HOSTNAME/$PROJECT_ID/hello:$SHORT_SHA
  - id: Create a new release to the test environment
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - hello-release-$SHORT_SHA
      - --delivery-pipeline=hello-world
      - --region=europe-west1
      - --to-target=hello-world-tst

images:
  - $_GCR_HOSTNAME/$PROJECT_ID/hello:$SHORT_SHA

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logStreamingOption: STREAM_ON