steps:
  - id: Deploy service using skaffold
    name: gcr.io/k8s-skaffold/skaffold:v2.13.2
    entrypoint: 'bash'
    args:
      - -c
      - |
        skaffold run \
          --default-repo=$_GCR_HOSTNAME/$PROJECT_ID \
          --label=commitSha=$COMMIT_SHA \
          --cloud-run-project=joaonrb-e5-cloud-deploy \
          --cloud-run-location=europe-west1

#  - id: Build the image
#    name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - -t=$_GCR_HOSTNAME/$PROJECT_ID/hello:$COMMIT_SHA
#      - .
#  - id: Push the image to Artifact Registry
#    name: gcr.io/cloud-builders/docker
#    args:
#      - push
#      - $_GCR_HOSTNAME/$PROJECT_ID/hello:$COMMIT_SHA
#  - id: Roulout the release to the test environment
#    name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
#    entrypoint: gcloud
#    args:
#      - deploy
#      - rollouts
#      - advance
#      - hello-app
#      - --delivery-pipeline=hello-app
#      - --region=europe-west1
#      - --release=hello-tst
#
#images:
#  - $_GCR_HOSTNAME/$PROJECT_ID/hello:$COMMIT_SHA

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logStreamingOption: STREAM_ON