apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: hello-cloud-deploy
deploy:
  cloudrun: {}
build:
  artifacts:
    - image: hello-cloud-deploy
      context: .
      docker:
        dockerfile: Dockerfile